on: [push]

name: ManagementGroupDeployment

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Login via Az module
      uses: azure/actions/login@v1
      with:
        creds: '${{secrets.AZURE_CREDENTIALS}}'
        enable-AzPSSession: true 
        
    - name: Run Azure PowerShell script
      uses: azure/powershell@v1
      with:
        inlineScript: |
          $inputObject = @{
            DeploymentName        = 'alz-MGDeployment-{0}' -f (-join (Get-Date -Format 'yyyyMMddTHHMMssffffZ')[0..63])
            Location              = 'EastUS'
            TemplateFile          = "infra-as-code/bicep/modules/managementGroups/managementGroups.bicep"
            TemplateParameterFile = 'infra-as-code/bicep/modules/managementGroups/parameters/managementGroups.parameters.all.json'}
          New-AzTenantDeployment @inputObject
        azPSVersion: "latest"