on: [push]

name: ManagementGroupDeployment

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Login via Az module
      uses: azure/actions/login@v1
      with:
        creds: '${{secrets.AZURE_CREDENTIALS}}'
        enable-AzPSSession: true 
        
    - name: Run Azure PowerShell script
      shell: pwsh
      run: |
        Install-Module -Name Az -Repository PSGallery -Confirm -Force
        Get-AzContext
