on: [push]

name: ManagementGroupDeployment

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Login via Az module
      uses: azure/actions/login@v1
      with:
        creds: '${{secrets.AZURE_CREDENTIALS}}'
        enable-AzPSSession: true 
        
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az account show
