on: [push]

name: ManagementGroupDeployment

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Login via Az module
      uses: azure/actions/login@v1
      with:
        creds: '${{secrets.AZURE_CREDENTIALS}}'
        enable-AzPSSession: true 
        
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          ls
          dateYMD=$(date +%Y%m%dT%H%M%S%NZ)
          NAME="alz-MGDeployment-${dateYMD}"
          LOCATION="eastus"
          TEMPLATEFILE="/home/runner/work/FORKEDALZ-BICEP/ALZ-Bicep/infra-as-code/bicep/modules/managementGroups/managementGroups.bicep"
          PARAMETERS="@infra-as-code/bicep/modules/managementGroups/parameters/managementGroups.parameters.all.json"
          az deployment tenant create --name ${NAME:0:63} --location $LOCATION --template-file $TEMPLATEFILE --parameters $PARAMETERS
